server:
  port: 8081  
  
spring:
  datasource:
    url: jdbc:mysql://172.16.2.17:3306/db_usuarios
    username: root
    password: 1234
    
#Actualiza aï¿½adiendo columnas pero no regenera la tabla
  jpa:
    hibernate:
      ddl-auto: update

# Cuando hay cambios, eliminar la tabla y datos, y la vuelve a crear
# spring.jpa.hibernate.ddl-auto=create
